### ISSUE TITLE
HTTP Error 500: INTERNAL SERVER ERROR when loading omnipose model

### ISSUE THREAD

**Issue by ptlzon** [SchmollerLab/Cell_ACDC#483]
### Description:

After setting model type and GPU option in omnipose parameters, clicking OK produced the following errors.
I'm using CellACDC in a company environment with proxy settings.
I am not familari with networking stuff, but I already set HTTP_PROXY, HTTPS_PROXY, FTP_PROXY user environment and other software doesn't have problem with connecting to the internet.
In addition, CellACDC could connect to internet and download model weights and install libraries with other segmentation model such as SAM, cellpose.

![image](https://github.com/SchmollerLab/Cell_ACDC/assets/157567305/2535efa1-9dee-429e-b69b-82c1606fa45a)

### Terminal output:

```Shell
22-02-2024, 09:48:07 - cellacdc-logger-acdc_gui - INFO:
------------------------
Initializing GUI v1.4.23
------------------------

22-02-2024, 09:48:07 - cellacdc-logger-acdc_gui - INFO:
------------------------
Initiliazing profilers...
------------------------

22-02-2024, 09:48:07 - cellacdc-logger-acdc_gui - INFO:
------------------------
GUI ready.
------------------------

22-02-2024, 09:48:28 - cellacdc-logger-acdc_gui - INFO:
------------------------
Opening FILE "None"
------------------------

22-02-2024, 09:48:31 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loading from D:/tmp/grayscale/20240222_072328_acdc/Images
------------------------

22-02-2024, 09:48:31 - cellacdc-logger-acdc_gui - INFO:
------------------------
Using .tif file (D:/tmp/grayscale/20240222_072328_acdc/Images\9Z15003-1_crop.tif)...
------------------------

22-02-2024, 09:48:31 - cellacdc-logger-acdc_gui - INFO:
------------------------
Reading  channel metadata...
------------------------

22-02-2024, 09:48:31 - cellacdc-logger-acdc_gui - INFO:
------------------------
Lazy loader paused.
------------------------

22-02-2024, 09:48:31 - cellacdc-logger-acdc_gui - INFO:
------------------------
Closing lazy loader...
------------------------

22-02-2024, 09:48:33 - cellacdc-logger-acdc_gui - INFO:
------------------------
Segmentation filename: D:/tmp/grayscale/20240222_072328_acdc/Images\9Z15003-1_crop_segm.npz
------------------------

22-02-2024, 09:48:33 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loading 20240222_072328_acdc\Images\9Z15003-1_crop.tif...
------------------------

22-02-2024, 09:48:33 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loaded paths:
Segmentation file name: 9Z15003-1_crop_segm.npz
ACDC output file name 9Z15003-1_crop_acdc_output.csv
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Full dataset shape = Not Loaded
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loaded dataset shape = (1, 424, 567)
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Number of frames = 1
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Number of z-slices per frame = 1
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Creating graphical items...
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Initializing measurements...
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Setting GUI mode to "Snapshots"...
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
20240222_072328_acdc || Basename: 9Z15003-1_crop || Segmented channel:  || Segmentation file name: _segm.npz
------------------------

22-02-2024, 09:48:36 - cellacdc-logger-acdc_gui - INFO:
------------------------
Autosaving worker started.
------------------------

22-02-2024, 09:48:47 - cellacdc-logger-acdc_gui - INFO:
------------------------
Importing omnipose...
------------------------

22-02-2024, 09:49:07 - cellacdc-logger-acdc_gui - ERROR:
------------------------
Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2674, in init_segm_model
    model = acdcSegment.Model(**init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\models\omnipose\acdcSegment.py", line 31, in __init__
    self.model = models.Cellpose(
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 107, in __init__
    self.pretrained_model = [model_path(model_type, j, torch) for j in model_range]
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 107, in <listcomp>
    self.pretrained_model = [model_path(model_type, j, torch) for j in model_range]
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 35, in model_path
    return cache_model_path(basename)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 49, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 373, in inner_function
    result = func(self, *args, **kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\gui.py", line 13950, in repeatSegm
    model = myutils.init_segm_model(acdcSegment, posData, win.init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2676, in init_segm_model
    model = acdcSegment.Model(segm_data, **init_kwargs)
TypeError: __init__() got multiple values for argument 'model_type'

------------------------
Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2674, in init_segm_model
    model = acdcSegment.Model(**init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\models\omnipose\acdcSegment.py", line 31, in __init__
    self.model = models.Cellpose(
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 107, in __init__
    self.pretrained_model = [model_path(model_type, j, torch) for j in model_range]
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 107, in <listcomp>
    self.pretrained_model = [model_path(model_type, j, torch) for j in model_range]
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 35, in model_path
    return cache_model_path(basename)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 49, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 373, in inner_function
    result = func(self, *args, **kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\gui.py", line 13950, in repeatSegm
    model = myutils.init_segm_model(acdcSegment, posData, win.init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2676, in init_segm_model
    model = acdcSegment.Model(segm_data, **init_kwargs)
TypeError: __init__() got multiple values for argument 'model_type'
22-02-2024, 09:49:07 - cellacdc-logger-acdc_gui - INFO:
------------------------
====================================
WARNING: Cell-ACDC is in error state. Please, restart.
====================================
------------------------
```

### Version information:

```Shell
(acdc) D:\tmp>python -c "import sys; print(sys.version); import platform; print(platform.platform()); import cellacdc; print(f'Cell-ACDC version: {cellacdc.__version__}')"
3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:29:04) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Cell-ACDC version: 1.4.23
```

**Comment by ElpadoCan** [comment]
Hi @ptlzon, apparently this seems to be a problem with omnipose/cellpose automatic download of the model. There is already an issue open on the omnipose page we need to wait that they fix it https://github.com/kevinjohncutler/omnipose/issues/79. 

In the meantime I will check how you can manually download the model. I will keep you updated.

**Comment by ElpadoCan** [comment]
Ok, unfortunately, the link to the model does not work so until they fix it I don't know where you can download the model, sorry about that. This used to be the correct link https://www.cellpose.org/models/bact_phase_omni

**Comment by ptlzon** [comment]
Hi Francesco,

Thanks for the info. I'm noted.

________________________________

**Comment by ElpadoCan** [comment]
Hi @ptlzon, I didn't release a new version on PyPi yet, because I need to finish some tests, but I fixed this on the GitHub repo. I uploaded the omnipose models on our internal server and automatic download should now work. 

To upgrade, activate the `acdc` environment and run the command 
```
pip install --upgrade "git+https://github.com/SchmollerLab/Cell_ACDC"
```

Note that if you are on Windows and it complains that the command `git` is missing you need to install Git from here first https://git-scm.com/download/win. 

The other option is to wait until I release a new version on PyPi. I will do that soon. Have a good weekend! 

Cheers,
Francesco

**Comment by ElpadoCan** [comment]
Hi  @ptlzon,

I recently released `v1.3.24` which implements what we discussed here. 

To upgrade, activate the acdc environment and run the command `pip install --upgrade cellacdc`. Let me know if it works now, thanks!

**Comment by ptlzon** [comment]
Hi @ElpadoCan 

Thanks for your notice.
I upgraded acdc as your instruction but got error complaining about  repeatSegm function.
After clicking omnipose menu in Segment menu, the command line windows showed downloading some 71.5 MB file, but without any explanation (that is not really a problem though) but in the log the HTTP error still persisted.
The setting parameters for omnipose displayed correctly, I let it as default (or previously saved ones) with "cyto2_omnipose" model, clicked OK and the error came out.

Thanks for your check.

```
22-03-2024, 07:15:27 - cellacdc-logger-acdc_gui - INFO:
------------------------
Initializing GUI v1.4.24
------------------------

22-03-2024, 07:15:27 - cellacdc-logger-acdc_gui - INFO:
------------------------
Initiliazing profilers...
------------------------

22-03-2024, 07:15:28 - cellacdc-logger-acdc_gui - INFO:
------------------------
GUI ready.
------------------------

22-03-2024, 07:15:31 - cellacdc-logger-acdc_gui - INFO:
------------------------
Opening FILE "None"
------------------------

22-03-2024, 07:15:34 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loading from D:/tmp/grayscale/20240222_072328_acdc/Images
------------------------

22-03-2024, 07:15:34 - cellacdc-logger-acdc_gui - INFO:
------------------------
Using .tif file (D:/tmp/grayscale/20240222_072328_acdc/Images\9Z15003-1_crop.tif)...
------------------------

22-03-2024, 07:15:34 - cellacdc-logger-acdc_gui - INFO:
------------------------
Reading  channel metadata...
------------------------

22-03-2024, 07:15:34 - cellacdc-logger-acdc_gui - INFO:
------------------------
Lazy loader paused.
------------------------

22-03-2024, 07:15:34 - cellacdc-logger-acdc_gui - INFO:
------------------------
Closing lazy loader...
------------------------

22-03-2024, 07:15:41 - cellacdc-logger-acdc_gui - INFO:
------------------------
Segmentation filename: D:/tmp/grayscale/20240222_072328_acdc/Images\9Z15003-1_crop_segm.npz
------------------------

22-03-2024, 07:15:45 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loading 20240222_072328_acdc\Images\9Z15003-1_crop.tif...
------------------------

22-03-2024, 07:15:45 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loaded paths:
Segmentation file name: 9Z15003-1_crop_segm.npz
ACDC output file name 9Z15003-1_crop_acdc_output.csv
------------------------

22-03-2024, 07:15:45 - cellacdc-logger-acdc_gui - INFO:
------------------------
Full dataset shape = Not Loaded
------------------------

22-03-2024, 07:15:45 - cellacdc-logger-acdc_gui - INFO:
------------------------
Loaded dataset shape = (1, 424, 567)
------------------------

22-03-2024, 07:15:45 - cellacdc-logger-acdc_gui - INFO:
------------------------
Number of frames = 1
------------------------

22-03-2024, 07:15:45 - cellacdc-logger-acdc_gui - INFO:
------------------------
Number of z-slices per frame = 1
------------------------

22-03-2024, 07:15:46 - cellacdc-logger-acdc_gui - INFO:
------------------------
Creating graphical items...
------------------------

22-03-2024, 07:15:46 - cellacdc-logger-acdc_gui - INFO:
------------------------
Initializing measurements...
------------------------

22-03-2024, 07:15:46 - cellacdc-logger-acdc_gui - INFO:
------------------------
Setting GUI mode to "Snapshots"...
------------------------

22-03-2024, 07:15:46 - cellacdc-logger-acdc_gui - INFO:
------------------------
20240222_072328_acdc || Basename: 9Z15003-1_crop || Segmented channel:  || Segmentation file name: _segm.npz
------------------------

22-03-2024, 07:15:46 - cellacdc-logger-acdc_gui - INFO:
------------------------
Autosaving worker started.
------------------------

22-03-2024, 07:17:53 - cellacdc-logger-acdc_gui - INFO:
------------------------
Importing omnipose...
------------------------

22-03-2024, 07:18:29 - cellacdc-logger-acdc_gui - ERROR:
------------------------
Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2827, in init_segm_model
    model = acdcSegment.Model(**init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\models\omnipose\acdcSegment.py", line 31, in __init__
    self.model = models.Cellpose(
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 130, in __init__
    self.pretrained_size = size_model_path(model_type, torch)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 40, in size_model_path
    return cache_model_path(basename)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 49, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 388, in inner_function
    result = func(self, *args, **kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\gui.py", line 14099, in repeatSegm
    model = myutils.init_segm_model(acdcSegment, posData, win.init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2829, in init_segm_model
    model = acdcSegment.Model(segm_data, **init_kwargs)
TypeError: __init__() got multiple values for argument 'model_type'

------------------------
Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2827, in init_segm_model
    model = acdcSegment.Model(**init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\models\omnipose\acdcSegment.py", line 31, in __init__
    self.model = models.Cellpose(
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 130, in __init__
    self.pretrained_size = size_model_path(model_type, torch)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 40, in size_model_path
    return cache_model_path(basename)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\models.py", line 49, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellpose_omni\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\miniconda3_windows\envs\acdc\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 388, in inner_function
    result = func(self, *args, **kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\gui.py", line 14099, in repeatSegm
    model = myutils.init_segm_model(acdcSegment, posData, win.init_kwargs)
  File "D:\miniconda3_windows\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 2829, in init_segm_model
    model = acdcSegment.Model(segm_data, **init_kwargs)
TypeError: __init__() got multiple values for argument 'model_type'
22-03-2024, 07:18:29 - cellacdc-logger-acdc_gui - INFO:
------------------------
====================================
WARNING: Cell-ACDC is in error state. Please, restart.
====================================
------------------------


```

**Comment by ElpadoCan** [comment]
Ok wow, it's the same HTTP error as before. It is still trying to download from the cellpose website. Let me have a look, thanks for reporting this

**Comment by ElpadoCan** [comment]
Ok, I found the problem. The model `size_cyto2_omnitorch_0.npy` is missing on both the cellpose website and the temporary repository created on the omnipose issue (see here https://github.com/kevinjohncutler/omnipose/issues/79#issuecomment-2014735241).

That model is needed by the `cyto2_omni` model but not by the bacterial models (the ones I was testing). Since I never tried the `cyto2_omni` mode I never realised that the size model was missing. 

Unfortunately, I don't have a copy of that model so we need to wait for someone to upload it somewhere and then I can upload it to our server. I already asked them on the omnipose GitHub page. Sorry about that but for the moment we can only wait.

**Comment by ElpadoCan** [comment]
Hi @ptlzon, I just published `v1.4.25` which hopefully fixes this. I got the size model and uploaded to our server so next time you try omnipose it should download that model too. 

Let me know if it works, thanks!

**Comment by ptlzon** [comment]
Hi @ElpadoCan

I just tried with the update and cyto2_omni worked now.
Thanks a lot.
